const WORDS_REQUEST = 'WORDS_REQUEST';
const WORDS_SUCCESS = 'WORDS_SUCCESS';
const WORDS_FAILURE = 'WORDS_FAILURE';
const WORDS_CLEAR = 'WORDS_CLEAR';
const WORDS_LETTER_SET = 'WORDS_LETTER_SET';

export const types = {
	WORDS_REQUEST,
	WORDS_SUCCESS,
	WORDS_FAILURE,
	WORDS_CLEAR,
	WORDS_LETTER_SET
};