export const SET_ERROR_PAGINATION = 'SET_ERROR_PAGINATION';
export const SET_LOADING_PAGINATION = 'SET_LOADING_PAGINATION';

export const SET_ERROR_SUGGESTIONS = 'SET_ERROR_SUGGESTIONS';
export const SET_LOADING_SUGGESTIONS = 'SET_LOADING_SUGGESTIONS';

export const PAGINATION_GET_SUCCESS = 'PAGINATION_GET_SUCCESS';
export const CLEAR_PAGINATION_ELEMENTS = 'CLEAR_PAGINATION_ELEMENTS';

export const SUGGESTIONS_GET_SUCCESS = 'SUGGESTIONS_GET_SUCCESS';
export const CLEAR_SUGGESTIONS_ELEMENTS = 'CLEAR_SUGGESTIONS_ELEMENTS';

export const SET_ELEMENT_TO_SHOW = 'SET_ELEMENT_TO_SHOW';
export const CLEAR_ELEMENT_TO_SHOW = 'CLEAR_ELEMENT_TO_SHOW';