const SUGGESTIONS_CLEAR = 'SUGGESTIONS_CLEAR';

const SUGGESTIONS_REQUEST = 'SUGGESTIONS_REQUEST';
const SUGGESTIONS_SUCCESS = 'SUGGESTIONS_SUCCESS';
const SUGGESTIONS_FAILURE = 'SUGGESTIONS_FAILURE';

export const types = {
	SUGGESTIONS_CLEAR,
	SUGGESTIONS_REQUEST,
	SUGGESTIONS_SUCCESS,
	SUGGESTIONS_FAILURE,
};