const WORD_DETAILS_SET = 'WORD_DETAILS_SET';
const WORD_DETAILS_CLEAR = 'WORD_DETAILS_CLEAR';

const WORD_DETAILS_REQUEST = 'WORD_DETAILS_REQUEST';
const WORD_DETAILS_SUCCESS = 'WORD_DETAILS_SUCCESS';
const WORD_DETAILS_FAILURE = 'WORD_DETAILS_FAILURE';

export const types = {
	WORD_DETAILS_SET,
	WORD_DETAILS_CLEAR,
	WORD_DETAILS_REQUEST,
	WORD_DETAILS_SUCCESS,
	WORD_DETAILS_FAILURE,
};