export const SET_ERROR = 'SET_ERROR';
export const SET_LOADING = 'SET_LOADING';
export const PAGINATION_GET_SUCCESS = 'PAGINATION_GET_SUCCESS';
export const CLEAR_PAGINATION_ELEMENTS = 'CLEAR_PAGINATION_ELEMENTS';